#SSID TWILLIO
SSID = ''
#AUTH TOKEN TWILLIO
AUTH_TOKEN = ''
#SMS FROM NUMBER TWILLIO
FROM_NUMBER = ''
#SMS TO NUMBER REGISTERED
TO_NUMBER = ''

#BOLT API KEY
API_KEY = ''
#BOLT DEVICE ID
DEVICE_ID = ''
#FRAME SIZE
FRAME_SIZE = 10
#MULTIPLICATION FACTOR
MUL_FACTOR = 3
